### ISSUE TITLE
Failed Donwload Package

### ISSUE THREAD

**Issue by js5285** [Cipfahim/Blog-System-in-Laravel#1]
Hi, 

While I composer install, it showing "Failed to clone https://github.com/vlucas/phpdotenv.git, git was not found, check that it is in stalled and in your PATH env".

How can I solve this? 

Thanks.

**Comment by Cipfahim** [comment]
bro you need to install git first. If you are using windows
https://git-scm.com/download/win or if you are on linux then sudo apt
install git

**Comment by js5285** [comment]
Hi Fahim, 

I have installed Git, but it show attached screenshot. 

![error](https://user-images.githubusercontent.com/9911708/43366899-358bded4-9377-11e8-84a8-d0b4d24c46d4.png)

**Comment by dalisonspy** [comment]
I downloaded your project to study, installed and configured the database, migrate and everything, I registered a new user but when I try to login I'm giving this error, I'm new to laravel, can you help me ??

![image](https://user-images.githubusercontent.com/22480982/43643766-e5aa6e28-971b-11e8-85a5-c654e422a873.png)

**Comment by Cipfahim** [comment]
bro you didn't create role  use this command

 php artisan migrate:fresh --seed

after that try again to register a new user.
everything will be fine i hope.

**Comment by IsoftTech** [comment]
To solve this, delete the composer.lock file and run composer install

**Comment by js5285** [comment]
I found out why composer install failed, because antivirus encrypt the connection. Problem solved now.
